spring.config.import=optional:file:./CampusNexus/backend/.env[.properties]

spring.application.name=campus-nexus-backend
server.port=8081
# Aiven Cloud Database Connection
spring.datasource.url=jdbc:mysql://paf-campus-db-mwsahirumax96-4c4c.d.aivencloud.com:23565/demo?ssl-mode=REQUIRED
spring.datasource.username=${DB_UN}
spring.datasource.password=${DB_PWD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

##google login details
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email


# GitHub Login Details
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}