spring.config.import=optional:file:.env[.properties],optional:file:CampusNexus/backend/.env[.properties]

spring.application.name=campus-nexus-backend
server.port=8081
# Aiven Cloud Database Connection
spring.datasource.url=jdbc:mysql://paf-campus-db-mwsahirumax96-4c4c.d.aivencloud.com:23565/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
